---
- name: Setup Python Dev Environment
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install Python3
      package:
        name: python3
        state: latest
    - name: Install pip
      package:
        name: python3-pip
        state: latest
    - name: Install necessary Python packages
      pip:
        name:
          - numpy
          - pandas
          - jupyter
          - matplotlib
          - scipy
          - seaborn
